var express = require('express');
var router = express.Router();
var Course = require('../models/course');

// const courses = require('../seed/data.json').courses;
// const users = require('../seed/data.json').users;
console.log(Course);
// console.log(courses[2]);
// console.log(users[0]);
// let course = [];
// // Get all copurses data in the format of json
router.get('/courses', async(req, res) => {
  const courses = await Course.findAll();
  res.render('index', { courses });
});

// Get a unique course get it from its USERID.
// I am having problem with this one how am I going to get autogenerated ID

// router.get('/courses/:id', async(req, res) => {
//   // console.log(courses[0].id) This is undefined
//   const course = await courses.find(course => course.id == req.params.id);
//   res.json(course);
// });



module.exports = router;
