var express = require('express');
var router = express.Router();
const courses = require('../seed/data.json').courses;
const users = require('../seed/data.json').users;

console.log(courses[2]);
console.log(users[0]);

// Get all copurses data in the format of json
router.get('/courses', (req, res) => {
  res.json(courses);
});

// Get a unique course get it from its USERID.
// I am having problem with this one how am I going to get autogenerated ID

router.get('/courses/:id', (req, res) => {
  console.log(courses[0].id)
  const course = courses.find(course => course.id == req.params.id);
  res.json(course);
});



module.exports = router;
